---
- name: make sure deployment path parent dir exists
  file:
    path: "{{ site_deployment_path|dirname }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  sudo: yes

- name: sync manage.py to deployment path
  command: rsync -av {{ site_build_path }}/manage.py {{ site_deployment_path }}/
  sudo: yes

- name: sync project code to deployment path
  command: rsync -avz --delete {{ site_build_path }}/{{ site_repo_name }} {{ site_deployment_path}}/
  sudo: yes

- name: delete the cloned project
  file:
    path: "{{ site_build_path }}"
    state: absent
  sudo: yes
