---
- name: make sure deployment path parent dir exists
  file:
    path: "{{ site_deployment_path|dirname }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  sudo: yes

- name: create app user
  user:
    name: "{{ site_app_user }}"
    home: "{{ site_deployment_path }}"
    createhome: no
    state: present
  sudo: yes

- name: clone project to build dir
  git:
    repo: "{{ site_repo_url }}"
    dest: "{{ site_build_path }}"
    accept_hostkey: yes

- name: set the app user as the owner
  file:
    path: "{{ site_build_path }}"
    owner: "{{ site_app_user }}"
    group: "{{ site_app_user }}"
    recurse: yes
    state: directory
  sudo: yes
